export const Userdetails = [
  {
    id: 1,
    image: "./images/avatar1.png",
    username: "Vidhi Kapadia",
    email: "vidhi@gmail.com",
    status: "active",
    owner: "owner",
    icon: "fa fa-trash-o",
  },
  {
    id: 2,
    image: "./images/avatar.png",
    username: "Naitik Shah",
    email: "naitik@gmail.com",
    status: "active",
    owner: "owner",
    icon: "fa fa-trash-o",
  },
  {
    id: 3,
    image: "./images/avatar.png",
    username: "Aman Gupta",
    email: "aman@gmail.com",
    status: "active",
    owner: "owner",
    icon: "fa fa-trash-o",
  },
  {
    id: 4,
    image: "./images/avatar1.png",
    username: "Kinjal Dave",
    email: "kinjal@gmail.com",
    status: "active",
    owner: "owner",
    icon: "fa fa-trash-o",
  },
  {
    id: 5,
    image: "./images/avatar.png",
    username: "Harsh Mehta ",
    email: "harsh@gmail.com",
    status: "active",
    owner: "owner",
    icon: "fa fa-trash-o",
  },
  {
    id: 6,
    image: "./images/avatar.png",
    username: "Samar Panchal",
    email: "samar@gmail.com",
    status: "active",
    owner: "owner",
    icon: "fa fa-trash-o",
  },
];
